name: notekeeper_flutter
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: ">=2.2.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  sqflite: ^1.3.0
  path_provider: ^1.6.5
  intl: ^0.16.1
  flutter_staggered_grid_view: ^0.3.0

  cupertino_icons: ^0.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter


flutter:

  uses-material-design: true

  fonts:
    - family: Titillium
      fonts:
        - asset: assets/fonts/Titillium-Bold.ttf
          weight: 700
        - asset: assets/fonts/Titillium-BoldItalic.ttf
          style: italic
          weight: 700
        - asset: assets/fonts/Titillium-Regular.ttf
        - asset: assets/fonts/Titillium-RegularItalic.ttf
          style: italic
        - asset: assets/fonts/Titillium-Light.ttf
          weight: 300
        - asset: assets/fonts/Titillium-LightItalic.ttf
          style: italic
          weight: 300
        - asset: assets/fonts/Titillium-Thin.ttf
          weight: 100
        - asset: assets/fonts/Titillium-ThinItalic.ttf
          style: italic
          weight: 100
